### ISSUE TITLE
Heya mates!

### ISSUE THREAD

**Issue by OndraPelanek** [mfernandes61/ghcourse1#4] opened 2024-11-29 15:26 UTC
# Heya pals!

Not a bad course **hey**

Some useful stuff [here]{https://cambiotraining.github.io/reproducibility-training/git.html}

It's getting a bit info heavy with git but still cool

**Comment by mfernandes61** [comment] 2024-11-29 15:28
Duplicate of previous issue - **closing**

**Closed by mfernandes61** 2024-11-29 15:28 UTC
